// apps/web/components/Brand.tsx
import Link from 'next/link';

export function Brand({ href = '/' }: { href?: string }) {
  return (
    <Link href={href} className="group flex items-center gap-2">
      <span className="flex h-7 w-7 items-center justify-center rounded-md bg-accent text-accent-fg font-serif text-[16px] font-semibold">
        초
      </span>
      <span className="font-serif text-[18px] text-fg-1 group-hover:text-accent transition duration-fast">
        초희
      </span>
    </Link>
  );
}

// packages/ui/src/components/Brand.svelte
<script lang="ts">
  interface Props {
    href?: string;
  }
  let { href = '/' }: Props = $props();
</script>

<a {href} class="inline-flex items-center gap-2">
  <span
    class="bg-accent text-accent-fg inline-flex h-7 w-7 items-center justify-center rounded-md font-serif text-base"
    aria-hidden="true"
  >
    초
  </span>
  <span class="text-fg-1 text-sm font-medium tracking-tight">Chohee</span>
</a>
