// packages/ui/src/components/Chip.tsx
import type { ButtonHTMLAttributes, ReactNode } from 'react';
import { cn } from '../utils';

export interface ChipProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  active?: boolean;
  size?: 'sm' | 'md' | 'lg';
  icon?: ReactNode;
}

const sizes = {
  sm: 'h-6 px-2.5 text-[11px]',
  md: 'h-7 px-3 text-[12px]',
  lg: 'h-9 px-4 text-[13px]',
};

export function Chip({
  className,
  active = false,
  size = 'md',
  icon,
  children,
  type = 'button',
  ...rest
}: ChipProps) {
  return (
    <button
      type={type}
      className={cn(
        'inline-flex items-center gap-1.5 rounded-pill border font-medium transition duration-fast',
        sizes[size],
        active
          ? 'border-accent/40 bg-accent-soft text-accent'
          : 'border-bd-1 bg-bg-2 text-fg-2 hover:bg-bg-3 hover:text-fg-1',
        className,
      )}
      {...rest}
    >
      {icon}
      {children}
    </button>
  );
}

// packages/ui/src/components/Chip.svelte
<script lang="ts">
  import { cn } from '../utils';

  interface Props {
    selected?: boolean;
    disabled?: boolean;
    onclick?: (e: MouseEvent) => void;
    type?: 'button' | 'submit';
    class?: string;
    children?: import('svelte').Snippet;
  }

  let {
    selected = false,
    disabled = false,
    onclick,
    type = 'button',
    class: klass = '',
    children,
  }: Props = $props();
</script>

<button
  {type}
  {disabled}
  {onclick}
  aria-pressed={selected}
  class={cn(
    'inline-flex items-center gap-1 rounded-pill border px-3 py-1 text-xs transition',
    selected
      ? 'bg-accent/15 text-accent border-accent/40'
      : 'bg-bg-2 text-fg-2 border-bd-1 hover:bg-bg-3',
    'disabled:opacity-50 disabled:cursor-not-allowed',
    klass,
  )}
>
  {@render children?.()}
</button>
