// packages/ui/src/components/ProgressBar.tsx
import { cn } from '../utils';

interface ProgressBarProps {
  value: number;
  max?: number;
  label?: string;
  showPercentage?: boolean;
  tone?: 'accent' | 'success' | 'warn';
  className?: string;
}

const toneFills = {
  accent: 'bg-accent',
  success: 'bg-success',
  warn: 'bg-warn',
};

export function ProgressBar({
  value,
  max = 100,
  label,
  showPercentage = false,
  tone = 'accent',
  className,
}: ProgressBarProps) {
  const clamped = Math.max(0, Math.min(value, max));
  const pct = (clamped / max) * 100;
  return (
    <div className={cn('flex flex-col gap-1.5', className)}>
      {(label || showPercentage) && (
        <div className="flex items-center justify-between text-[11px] text-fg-3">
          {label && <span>{label}</span>}
          {showPercentage && <span className="font-mono">{Math.round(pct)}%</span>}
        </div>
      )}
      <div
        className="h-1.5 w-full overflow-hidden rounded-pill bg-bg-3"
        role="progressbar"
        aria-valuenow={clamped}
        aria-valuemax={max}
        aria-valuemin={0}
      >
        <div
          className={cn('h-full rounded-pill transition-all duration-slow', toneFills[tone])}
          style={{ width: `${pct}%` }}
        />
      </div>
    </div>
  );
}

// packages/ui/src/components/ProgressBar.svelte
<script lang="ts">
  import { cn } from '../utils';

  interface Props {
    value: number; // 0..1
    indeterminate?: boolean;
    tone?: 'accent' | 'info' | 'success';
    label?: string;
    class?: string;
  }

  let { value, indeterminate = false, tone = 'accent', label, class: klass = '' }: Props = $props();
  const pct = $derived(Math.max(0, Math.min(1, value)) * 100);
  const TONE = { accent: 'bg-accent', info: 'bg-info', success: 'bg-success' };
</script>

<div class={cn('w-full', klass)}>
  {#if label}
    <div class="text-fg-3 mb-1 flex justify-between text-xs">
      <span>{label}</span>
      {#if !indeterminate}<span>{Math.round(pct)}%</span>{/if}
    </div>
  {/if}
  <div class="bg-bg-3 h-1.5 w-full overflow-hidden rounded-pill">
    {#if indeterminate}
      <div class={cn('h-full w-1/3 animate-pulse-soft', TONE[tone])}></div>
    {:else}
      <div
        class={cn('h-full transition-all', TONE[tone])}
        style:width="{pct}%"
      ></div>
    {/if}
  </div>
</div>
