// packages/ui/src/components/StatusBadge.tsx
import { cn } from '../utils';

export type MusicGenerationStatus = 'waiting' | 'generating' | 'complete' | 'revision';

interface StatusBadgeProps {
  status: MusicGenerationStatus;
  className?: string;
}

const statusLabels: Record<MusicGenerationStatus, string> = {
  waiting: '음악 대기 중',
  generating: '생성 중',
  complete: '완성',
  revision: '보완 요청',
};

const statusStyles: Record<MusicGenerationStatus, string> = {
  waiting:
    'border-status-waiting/30 bg-status-waiting/10 text-status-waiting',
  generating:
    'border-status-generating/30 bg-status-generating/10 text-status-generating',
  complete:
    'border-status-complete/30 bg-status-complete/10 text-status-complete',
  revision:
    'border-status-revision/30 bg-status-revision/10 text-status-revision',
};

const dotColors: Record<MusicGenerationStatus, string> = {
  waiting: 'bg-status-waiting',
  generating: 'bg-status-generating',
  complete: 'bg-status-complete',
  revision: 'bg-status-revision',
};

export function StatusBadge({ status, className }: StatusBadgeProps) {
  return (
    <span
      className={cn(
        'inline-flex items-center gap-1.5 rounded-pill border px-2.5 py-0.5 text-[11px] font-medium',
        statusStyles[status],
        className,
      )}
    >
      <span
        className={cn(
          'inline-block h-1.5 w-1.5 rounded-pill',
          dotColors[status],
          status === 'generating' && 'animate-pulse-soft',
        )}
        aria-hidden
      />
      {statusLabels[status]}
    </span>
  );
}

// packages/ui/src/components/StatusBadge.svelte
<script lang="ts" module>
  // 음악 생성 요청 상태에 대응하는 시각 표시.
  export type GenerationStatus =
    | 'pending'
    | 'in_progress'
    | 'completed'
    | 'rejected'
    | 'cancelled';

  const META: Record<GenerationStatus, { label: string; ring: string; dot: string }> = {
    pending: { label: '대기', ring: 'border-status-waiting/40 text-status-waiting', dot: 'bg-status-waiting' },
    in_progress: {
      label: '제안 받는 중',
      ring: 'border-status-generating/40 text-status-generating',
      dot: 'bg-status-generating animate-pulse-soft',
    },
    completed: {
      label: '채택됨',
      ring: 'border-status-complete/40 text-status-complete',
      dot: 'bg-status-complete',
    },
    rejected: { label: '거절', ring: 'border-danger/40 text-danger', dot: 'bg-danger' },
    cancelled: { label: '취소', ring: 'border-bd-2 text-fg-3', dot: 'bg-fg-4' },
  };
</script>

<script lang="ts">
  import { cn } from '../utils';

  interface Props {
    status: GenerationStatus;
    class?: string;
  }

  let { status, class: klass = '' }: Props = $props();
  const m = $derived(META[status]);
</script>

<span
  class={cn(
    'inline-flex items-center gap-1.5 rounded-pill border px-2.5 py-0.5 text-[11px] font-medium',
    m.ring,
    klass,
  )}
>
  <span class={cn('h-1.5 w-1.5 rounded-full', m.dot)} aria-hidden="true"></span>
  {m.label}
</span>
