// packages/ui/src/components/Textarea.svelte
<script lang="ts">
  import { cn } from '../utils';

  interface Props {
    name?: string;
    value?: string;
    placeholder?: string;
    rows?: number;
    required?: boolean;
    disabled?: boolean;
    invalid?: boolean;
    serif?: boolean;
    class?: string;
    oninput?: (e: Event) => void;
  }

  let {
    name,
    value = $bindable(''),
    placeholder,
    rows = 4,
    required,
    disabled,
    invalid,
    serif = false,
    class: klass = '',
    oninput,
  }: Props = $props();
</script>

<textarea
  {name}
  {placeholder}
  {rows}
  {required}
  {disabled}
  bind:value
  {oninput}
  aria-invalid={invalid ? 'true' : undefined}
  class={cn(
    'block w-full rounded-md border px-3 py-2 text-sm leading-relaxed',
    'bg-bg-2 text-fg-1 placeholder:text-fg-4',
    invalid ? 'border-danger' : 'border-bd-1',
    'focus:border-accent focus:outline-none',
    'disabled:opacity-50',
    serif && 'serif text-base',
    klass,
  )}
></textarea>

// packages/ui/src/components/Textarea.tsx
import { forwardRef, type TextareaHTMLAttributes } from 'react';
import { cn } from '../utils';

export interface TextareaProps extends TextareaHTMLAttributes<HTMLTextAreaElement> {
  label?: string;
  hint?: string;
  errorMessage?: string;
  serif?: boolean;
}

export const Textarea = forwardRef<HTMLTextAreaElement, TextareaProps>(function Textarea(
  { className, label, hint, errorMessage, serif = false, id, ...rest },
  ref,
) {
  const inputId = id ?? (label ? `ta-${label.replace(/\s+/g, '-').toLowerCase()}` : undefined);
  return (
    <div className="flex flex-col gap-1.5">
      {label && (
        <label htmlFor={inputId} className="text-[12px] text-fg-2">
          {label}
        </label>
      )}
      <textarea
        ref={ref}
        id={inputId}
        className={cn(
          'min-h-[120px] rounded-md border border-bd-1 bg-bg-3 px-3 py-2.5 text-[13px] text-fg-1 outline-none transition duration-fast',
          'placeholder:text-fg-3 focus:border-accent',
          serif && 'font-serif text-[16px] leading-[1.9]',
          errorMessage && 'border-danger/60',
          className,
        )}
        {...rest}
      />
      {(hint || errorMessage) && (
        <p className={cn('text-[11px]', errorMessage ? 'text-danger' : 'text-fg-3')}>
          {errorMessage ?? hint}
        </p>
      )}
    </div>
  );
});
