// packages/ui/src/components/Waveform.svelte
<script lang="ts">
  import { cn } from '../utils';

  interface Props {
    peaks: number[]; // 0..1 정규화된 값들
    progress?: number; // 0..1
    height?: number;
    bars?: number; // 표시할 막대 개수 (peaks를 다운샘플)
    class?: string;
  }

  let { peaks, progress = 0, height = 56, bars = 92, class: klass = '' }: Props = $props();

  const downsampled = $derived(downsample(peaks, bars));
  const cursor = $derived(Math.max(0, Math.min(1, progress)) * bars);

  function downsample(input: number[], target: number): number[] {
    if (input.length === 0) return Array.from({ length: target }, () => 0);
    if (input.length <= target) return input;
    const step = input.length / target;
    const out: number[] = [];
    for (let i = 0; i < target; i++) {
      const a = Math.floor(i * step);
      const b = Math.floor((i + 1) * step);
      let m = 0;
      for (let j = a; j < b; j++) if (input[j]! > m) m = input[j]!;
      out.push(m);
    }
    return out;
  }
</script>

<div
  class={cn('flex items-end gap-[2px] w-full', klass)}
  style:height="{height}px"
  role="img"
  aria-label="파형"
>
  {#each downsampled as v, i (i)}
    {@const h = Math.max(0.06, v)}
    {@const past = i < cursor}
    <div
      class={cn('flex-1 rounded-[1px] transition-colors', past ? 'bg-accent' : 'bg-bd-2')}
      style:height="{Math.round(h * height)}px"
    ></div>
  {/each}
</div>

// packages/ui/src/components/Waveform.tsx
'use client';
import { useMemo } from 'react';
import { cn } from '../utils';

interface WaveformProps {
  durationSeconds: number;
  positionSeconds?: number;
  peaks?: number[];
  bars?: number;
  onSeek?: (seconds: number) => void;
  playing?: boolean;
  className?: string;
}

function pseudoPeaks(count: number, seed: number): number[] {
  const out: number[] = [];
  let state = seed || 1;
  for (let i = 0; i < count; i++) {
    state = (state * 9301 + 49297) % 233280;
    const r = state / 233280;
    out.push(0.25 + r * 0.75);
  }
  return out;
}

export function Waveform({
  durationSeconds,
  positionSeconds = 0,
  peaks,
  bars = 92,
  onSeek,
  playing = false,
  className,
}: WaveformProps) {
  const data = useMemo(() => peaks ?? pseudoPeaks(bars, durationSeconds), [peaks, bars, durationSeconds]);
  const ratio = durationSeconds > 0 ? Math.min(positionSeconds / durationSeconds, 1) : 0;
  const playedIdx = Math.floor(ratio * data.length);
  return (
    <div
      className={cn('flex h-14 w-full items-end gap-[2px]', onSeek && 'cursor-pointer', className)}
      onClick={(e) => {
        if (!onSeek) return;
        const rect = (e.currentTarget as HTMLDivElement).getBoundingClientRect();
        const x = e.clientX - rect.left;
        const pct = Math.max(0, Math.min(1, x / rect.width));
        onSeek(pct * durationSeconds);
      }}
      role="slider"
      aria-valuemin={0}
      aria-valuemax={durationSeconds}
      aria-valuenow={positionSeconds}
    >
      {data.map((h, i) => {
        const isPlayed = i < playedIdx;
        const isHead = i === playedIdx && playing;
        return (
          <span
            key={i}
            className={cn(
              'w-[3px] origin-bottom rounded-pill transition-colors',
              isPlayed ? 'bg-accent' : 'bg-bd-2',
              isHead && 'animate-wave bg-accent',
            )}
            style={{ height: `${Math.max(4, h * 56)}px` }}
          />
        );
      })}
    </div>
  );
}
